services:
  nginx_fastcgi:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - local

  nginx:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - local
    depends_on:
      - nginx_fastcgi

networks:
  local:
    driver: bridge